import { afterEach, describe, expect, it } from 'vitest';
import { buildApp, NoopLogger } from '../app/server.js';
import { loadEnvironment } from '../config/environment.js';
const config = loadEnvironment({ NODE_ENV: 'test', DATABASE_URL: 'postgresql://localhost:5432/youtube_os' }); const headers = { authorization: 'Bearer mock-token', 'x-permissions': 'onboarding:access' }; const apps: Awaited<ReturnType<typeof buildApp>>[] = [];
afterEach(async () => Promise.all(apps.splice(0).map((app) => app.close()))); async function createApp() { const app = await buildApp({ config, logger: new NoopLogger() }); apps.push(app); return app; }
describe('Onboarding API', () => {
  it('requires authentication and onboarding:access', async () => { const app = await createApp(); expect((await app.inject({ method: 'GET', url: '/api/v1/onboarding/steps' })).statusCode).toBe(401); expect((await app.inject({ method: 'GET', url: '/api/v1/onboarding/steps', headers: { authorization: 'Bearer token' } })).statusCode).toBe(403); });
  it('returns nine steps and tracks progress', async () => { const app = await createApp(); const steps = await app.inject({ method: 'GET', url: '/api/v1/onboarding/steps', headers }); const submitted = await app.inject({ method: 'POST', url: '/api/v1/onboarding/step/profile', headers, payload: { userId: 'user-01', data: { name: 'Amina' } } }); expect(steps.json().data).toHaveLength(9); expect(submitted.json().data).toMatchObject({ progress: 11, complete: false }); });
  it('validates completion after every step', async () => { const app = await createApp(); expect((await app.inject({ method: 'POST', url: '/api/v1/onboarding/complete', headers, payload: { userId: 'user-02' } })).statusCode).toBe(400); for (const id of ['profile', 'goal', 'experience', 'niche', 'recommendations', 'channel', 'google', 'readiness', 'project']) await app.inject({ method: 'POST', url: `/api/v1/onboarding/step/${id}`, headers, payload: { userId: 'user-02', data: {} } }); const complete = await app.inject({ method: 'POST', url: '/api/v1/onboarding/complete', headers, payload: { userId: 'user-02' } }); expect(complete.json().data).toMatchObject({ progress: 100, complete: true }); expect(complete.json().data.recommendations).toHaveLength(3); });
});
