import { useState } from 'react';
import { RecommendationDisplay } from '../components/onboarding/RecommendationDisplay';
import { StepContent } from '../components/onboarding/StepContent';
import { StepNavigation } from '../components/onboarding/StepNavigation';
import { StepProgress } from '../components/onboarding/StepProgress';
const steps = [
  ['Create your profile', 'Add your creator identity and preferences.'], ['Choose your goal', 'Select Revenue, Brand, Media, or Education.'], ['Set experience level', 'Choose your experience level.'], ['Choose your niche', 'Select Video, Music, Shorts, or Education.'], ['Review AI recommendations', 'Review mock guidance for your choices.'], ['Create your channel', 'Create a mock channel workspace.'], ['Connect Google', 'Confirm a mock Google connection.'], ['Run AI readiness audit', 'Review a mock readiness audit.'], ['Create your first project', 'Create a mock content project.'],
].map(([title, description]) => ({ title: title!, description: description! }));
export function OnboardingPage() { const [index, setIndex] = useState(0); const [complete, setComplete] = useState(false); const next = () => index === steps.length - 1 ? setComplete(true) : setIndex(index + 1); return <section className="onboarding-page" aria-labelledby="onboarding-title"><div className="onboarding-header"><div><p className="eyebrow">Mock data only</p><h2 id="onboarding-title">Creator Onboarding</h2></div><span className="foundation-badge">{complete ? 'COMPLETE' : 'IN PROGRESS'}</span></div><StepProgress current={complete ? steps.length : index + 1} total={steps.length} /><div className="onboarding-grid"><StepContent step={steps[index]!} /><RecommendationDisplay recommendations={['Start with a focused weekly content cadence.', 'Run Quality Gate before publishing.', 'Create a short-form pilot project first.']} /></div><StepNavigation canGoBack={index > 0 && !complete} onBack={() => setIndex(index - 1)} onNext={next} /></section>; }
