import { PlatformError } from '../shared/errors.js';
import { loadGovernanceArtifact } from './governance-loader.js';
import type { CapabilityRecord, CapabilityRegistry } from './governance-schemas.js';

export interface CapabilitySummary { platformId: CapabilityRegistry['platformId']; registryVersion: string; total: number; implemented: number; notImplemented: number; verified: number; businessCapabilities: number; businessCapabilitiesNotImplemented: number; byLifecycleStatus: Readonly<Record<string, number>>; byCategory: Readonly<Record<string, number>> }
export interface CapabilityValidationResult { valid: true; authoritativeRegistry: 'governance/capability-registry.v1.json'; registryCount: 1; capabilityCount: number; duplicateCapabilityIds: readonly string[]; implementedWithoutVerifiedEvidence: readonly string[]; businessCapabilitiesNotImplemented: boolean; externalNetworkCommunication: false }

function countBy(capabilities: readonly CapabilityRecord[], field: 'lifecycleStatus' | 'capabilityCategory'): Readonly<Record<string, number>> { return Object.freeze(capabilities.reduce<Record<string, number>>((counts, capability) => { const value = capability[field]; counts[value] = (counts[value] ?? 0) + 1; return counts; }, {})); }
export async function getCapabilityRegistry(): Promise<Readonly<CapabilityRegistry>> { return loadGovernanceArtifact('capabilities'); }
export async function getCapabilitySummary(): Promise<Readonly<CapabilitySummary>> { const registry = await getCapabilityRegistry(); const business = registry.capabilities.filter((capability) => capability.capabilityCategory === 'YOUTUBE_BUSINESS'); return Object.freeze({ platformId: registry.platformId, registryVersion: registry.artifactVersion, total: registry.capabilities.length, implemented: registry.capabilities.filter((capability) => capability.implementationStatus === 'IMPLEMENTED').length, notImplemented: registry.capabilities.filter((capability) => capability.implementationStatus === 'NOT_IMPLEMENTED').length, verified: registry.capabilities.filter((capability) => capability.lifecycleStatus === 'VERIFIED').length, businessCapabilities: business.length, businessCapabilitiesNotImplemented: business.filter((capability) => capability.implementationStatus === 'NOT_IMPLEMENTED').length, byLifecycleStatus: countBy(registry.capabilities, 'lifecycleStatus'), byCategory: countBy(registry.capabilities, 'capabilityCategory') }); }
export async function getCapabilityById(capabilityId: string): Promise<Readonly<CapabilityRecord>> { const registry = await getCapabilityRegistry(); const capability = registry.capabilities.find((item) => item.capabilityId === capabilityId); if (!capability) throw new PlatformError(404, 'CAPABILITY_NOT_FOUND', `Capability ${capabilityId} was not found.`); return capability; }
export async function getCapabilityValidationResult(): Promise<Readonly<CapabilityValidationResult>> { const registry = await getCapabilityRegistry(); const seen = new Set<string>(); const duplicates = registry.capabilities.filter((capability) => { if (seen.has(capability.capabilityId)) return true; seen.add(capability.capabilityId); return false; }).map((capability) => capability.capabilityId); const withoutEvidence = registry.capabilities.filter((capability) => capability.implementationStatus === 'IMPLEMENTED' && capability.evidenceStatus !== 'VERIFIED').map((capability) => capability.capabilityId); const businessValid = registry.capabilities.filter((capability) => capability.capabilityCategory === 'YOUTUBE_BUSINESS').every((capability) => capability.implementationStatus === 'NOT_IMPLEMENTED'); return Object.freeze({ valid: true, authoritativeRegistry: 'governance/capability-registry.v1.json', registryCount: 1, capabilityCount: registry.capabilities.length, duplicateCapabilityIds: Object.freeze(duplicates), implementedWithoutVerifiedEvidence: Object.freeze(withoutEvidence), businessCapabilitiesNotImplemented: businessValid, externalNetworkCommunication: false }); }